# -*- coding: utf-8 -*-
"""Logic_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvudUb2iwXfvcmSdN-U5wc1Y7NMemgI0

# **Logic 4**
"""

print('==== LOGIC 4 ====')
print('\n')

# Konstanta
SIZE = 9
HALF_SIZE = 5



# Soal 1
print('Soal 1')
print()
for row in range(1, HALF_SIZE + 1):  # Loop untuk setiap baris
    for col in range(1, 2 * HALF_SIZE):  # Loop untuk setiap kolom
        if HALF_SIZE - row < col < HALF_SIZE + row:  # Cek batas segitiga
            # Hitung angka berdasarkan posisi relatif terhadap awal baris
            num = col - (HALF_SIZE - row)
            print(num, end='')  # Cetak angka
        else:
            print(' ', end='')  # Cetak spasi di luar area segitiga
    print()
print('\n\n')




# Soal 2
print('Soal 2')
print()
for row in range(1, SIZE - 3):  # Loop untuk setiap baris
    for col in range(1, SIZE + 1):  # Loop untuk setiap kolom
        if row <= col and row + col <= SIZE + 1:  # Kondisi untuk mencetak angka
            print(col - row + 1, end='')  # Cetak angka
        else:
            print(' ', end='')  # Cetak spasi di luar area segitiga
    print()
print('\n\n')




# Soal 3
print('Soal 3')
print()

# Bagian atas belah ketupat
for row in range(1, HALF_SIZE + 1):
    for col in range(1, 2 * HALF_SIZE):
        if HALF_SIZE - row < col < HALF_SIZE + row:  # Batas untuk mencetak angka
            print(col - (HALF_SIZE - row), end='')  # Cetak angka
        else:
            print(' ', end='')  # Cetak spasi
    print()

# Bagian bawah belah ketupat
for row in range(HALF_SIZE - 1, 0, -1):
    for col in range(1, 2 * HALF_SIZE):
        if HALF_SIZE - row < col < HALF_SIZE + row:  # Batas untuk mencetak angka
            print(col - (HALF_SIZE - row), end='')  # Cetak angka
        else:
            print(' ', end='')  # Cetak spasi
    print()
print('\n\n')




# Soal 4
print('Soal 4')
print()
for row in range(1, HALF_SIZE + 1):  # Loop untuk setiap baris
    for col in range(1, 2 * HALF_SIZE):  # Loop untuk setiap kolom
        if HALF_SIZE - row < col < HALF_SIZE + row:  # Batas untuk mencetak angka
            num = row - abs(HALF_SIZE - col)  # Hitung angka relatif
            print(2 * num - 1, end='')  # Cetak angka ganjil
        else:
            print(' ', end='')  # Cetak spasi
    print()
print('\n\n')




# Soal 5
print('Soal 5')
print()

# Loop untuk setiap baris
for row in range(HALF_SIZE, 0, -1):  # Mulai dari baris paling bawah dan bergerak ke atas
    # Cetak spasi di kiri
    for space in range(HALF_SIZE - row):  # Spasi bertambah setiap baris
        print(' ', end='')

    # Cetak angka ganjil sesuai pola
    for col in range(1, 2 * row):  # Menentukan jumlah angka yang dicetak
        # Menentukan angka ganjil, hanya angka ganjil yang dicetak
        num = 2 * col - 1  # Hitung angka ganjil
        if num <= (2 * row - 1):  # Hanya cetak angka ganjil yang sesuai panjang baris
            print(num, end='')

    # Cetak angka yang turun setelah mencapai angka tengah
    for col in range(2 * row - 3, 0, -2):  # Menurunkan angka setelah tengah
        print(col, end='')

    print()  # Pindah ke baris berikutnya
print('\n\n')



# Soal 6 (belah ketupat)
print('Soal 6')
print()

# Bagian atas belah ketupat
for row in range(1, HALF_SIZE + 1):
    # Cetak spasi di kiri
    for space in range(HALF_SIZE - row):
        print(' ', end='')

    # Cetak angka ganjil naik
    for col in range(1, row + 1):
        num = 2 * col - 1  # Hitung angka ganjil
        print(num, end='')

    # Cetak angka yang turun setelah angka tengah
    for col in range(row - 1, 0, -1):
        num = 2 * col - 1  # Hitung angka ganjil
        print(num, end='')

    print()  # Pindah ke baris berikutnya

# Bagian bawah belah ketupat
for row in range(HALF_SIZE - 1, 0, -1):
    # Cetak spasi di kiri
    for space in range(HALF_SIZE - row):
        print(' ', end='')

    # Cetak angka ganjil naik
    for col in range(1, row + 1):
        num = 2 * col - 1  # Hitung angka ganjil
        print(num, end='')

    # Cetak angka yang turun setelah angka tengah
    for col in range(row - 1, 0, -1):
        num = 2 * col - 1  # Hitung angka ganjil
        print(num, end='')

    print()  # Pindah ke baris berikutnya
print('\n\n')

|# Konstanta
HALF_SIZE = 5

# Soal 6 (belah ketupat)
print('Soal 6')
print()

# Bagian atas belah ketupat
for row in range(1, HALF_SIZE + 1):
    # Cetak spasi di kiri
    for space in range(HALF_SIZE - row):
        print(' ', end='')

    # Cetak angka ganjil naik
    for col in range(1, row + 1):
        num = 2 * col - 1  # Hitung angka ganjil
        print(num, end='')

    # Cetak angka yang turun setelah angka tengah
    for col in range(row - 1, 0, -1):
        num = 2 * col - 1  # Hitung angka ganjil
        print(num, end='')

    print()  # Pindah ke baris berikutnya

# Bagian bawah belah ketupat
for row in range(HALF_SIZE - 1, 0, -1):
    # Cetak spasi di kiri
    for space in range(HALF_SIZE - row):
        print(' ', end='')

    # Cetak angka ganjil naik
    for col in range(1, row + 1):
        num = 2 * col - 1  # Hitung angka ganjil
        print(num, end='')

    # Cetak angka yang turun setelah angka tengah
    for col in range(row - 1, 0, -1):
        num = 2 * col - 1  # Hitung angka ganjil
        print(num, end='')

    print()  # Pindah ke baris berikutnya

